name: FarmENGINE
version: @version@
main: de.fruxz.farmengine.Main
authors: [Fruxz]
description: FarmENGINE - The plugin to create an farmworld
website: https://github.com/TheFruxz
commands:
  farmworld:
    description: teleports you to the farmworld
    usage: /<command>
